DjangoProject/mysite/OnlineVotation/urls.py
from django.urls import path

from . import views

app_name="onlineVotation"
urlpatterns = [
    path('', views.indexPage, name="index"),
    path('habitant', views.habitantPage, name="habitant"),
    path('organizer', views.oraganizerPage, name="organizer"),
    path('admin', views.adminPage, name="admin"),
    path('newUser', views.newUserPage, name="newUser"),
    path('registerNewUser', views.registerNewUser, name="registerNewUser"),
    path('updateProvince/<int:id>', views.update_provinces, name="updateProvince")
]

DjangoProject/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('', include('OnlineVotation.urls')),
    path('admin/', admin.site.urls),
]

DjangoProject/mysite/polls/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('sum/<int:num1>/<int:num2>', views.sum)
]

DjangoProject/mysite/OnlineVotation/models.py
from django.db import models

# Create your models here.

DjangoProject/mysite/polls/models.py
from django.db import models

# Create your models here.

DjangoProject/mysite/OnlineVotation/forms/forms.py
from django import forms

class NameForm(forms.Form):

    def update_provinces(self, model_province):
        self.fields["provinces"].choices = model_province

    def update_a_c(self, model_ac):
        self.fields["autonomous_community"].choices = model_ac



    name = forms.CharField(label='Name:',
                                 max_length=100,
                                 required=True,
                                 widget=forms.TextInput(attrs={"placeholder" : "Name"}))
    sur_name = forms.CharField(label='Sur Name:',
                                 max_length=100,
                                 required=True,
                                 widget=forms.TextInput(attrs={"placeholder" : "SurName"}))
    phone_number = forms.IntegerField(label='Phone number:',
                                      required=True,
                                      widget=forms.NumberInput(attrs={"placeholder" : "Phone Number"}))
    email = forms.EmailField(label='Email',
                             required=True,
                             widget=forms.EmailInput(attrs={"placeholder" : "Email"}))

    autonomous_community = forms.ChoiceField(label='Autonomous Community',
                                       required=True,
                                       choices=[],
                                  widget=forms.Select(attrs={"class" : "selector", "onchange" : "updateProvinces(this)"}))

    provinces = forms.ChoiceField(label='Provinces',
                                       required=True,
                                       choices=[],
                                  widget=forms.Select(attrs={"class" : "selector"}))

    birthday = forms.DateField(label='Birthday',
                               required=True,
                               widget=forms.DateInput(attrs={"placeholder" : "Birthday"}),
                               input_formats=['%m/%d/%Y', '%m/%d/%y'])
    password = forms.CharField(label='Password',
                               required=True,
                               widget=forms.PasswordInput(attrs={"placeholder" : "Password"}))
    repeat_password = forms.CharField(label='Repeat Password',
                               required=True,
                               widget=forms.PasswordInput(attrs={"placeholder" : "Repeat Password"}))

DjangoProject/mysite/OnlineVotation/views.py
import json

from django.http import HttpResponseRedirect
from django.shortcuts import render, HttpResponse


# Create your views here.
from .forms.forms import NameForm


def indexPage(request):
    return render(request, "OnlineVotation/home/home.html")


def habitantPage(request):
    autorized = False
    if not autorized:
        return render(request, "OnlineVotation/habitant/habitantLoginPage.html")
    return render(request, "OnlineVotation/habitant/habitant.html")


def oraganizerPage(request):
    autorized = False
    if not autorized:
        return render(request, "OnlineVotation/shared/commonLoginPage.html")
    return render(request, "OnlineVotation/organizer/organizer.html")


def adminPage(request):
    autorized = False
    if not autorized:
        return render(request, "OnlineVotation/shared/commonLoginPage.html")
    return render(request, "OnlineVotation/admin/admin.html")

def newUserPage(request):
    form = NameForm()
    form.update_provinces([("1", "Malaga"),("2", "Sevilla"),("3", "Granada")])
    form.update_a_c([("1", "Andalucia"),("2", "Galicia"),("3", "Canarias")])
    return render(request, "OnlineVotation/newUser/newUser.html", {"form" : form})

def registerNewUser(request):
    if request.method == 'POST':
        form = NameForm(request.POST)
        form.update_provinces([("1", "Malaga"),("2", "Sevilla"),("3", "Granada")])
        if form.is_valid():
            return HttpResponseRedirect('/thanks/')
        else:
            return render(request, "OnlineVotation/newUser/newUser.html", {"form" : form, "errors" : form.errors})
    return HttpResponse('')

class Province:
    id: int
    name: str

    def __init__(self, id: int, name: str):
        self.id = id
        self.name = name


def update_provinces(request, id):
    if id == 1:
        result = [Province("1", "A"), Province("2", "A"), Province("3", "A")]
    elif id == 2:
        result = [Province("1", "B"), Province("2", "B"), Province("3", "B")]
    elif id == 3:
        result = [Province("1", "C"), Province("2", "C"), Province("3", "C")]

    return HttpResponse(json.dumps([ob.__dict__ for ob in result]), content_type="application/json")

DjangoProject/mysite/polls/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return HttpResponse("Hello World!!!")

def sum(request, num1:int, num2:int) -> HttpResponse:
    return HttpResponse(f"Sum is: {num1 + num2}")

DjangoProject/mysite/OnlineVotation/templates/OnlineVotation/admin/admin.html
{% extends "OnlineVotation/shared/base.html" %}

{% load static %}

{% block title %}
    Habitant
{% endblock %}

{% block content %}
    <div>
        <p>Main Admin page</p>
    </div>
{% endblock %}

DjangoProject/mysite/OnlineVotation/templates/OnlineVotation/habitant/habitant.html
{% extends "OnlineVotation/shared/base.html" %}

{% load static %}

{% block title %}
    Habitant
{% endblock %}

{% block content %}
<div>
    <p>Main Habitant page</p>
</div>
{% endblock %}

DjangoProject/mysite/OnlineVotation/templates/OnlineVotation/habitant/habitantLoginPage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>OVLogin</title>
    {% load static %}
    <link href="{% static 'OnlineVotation/css/habitant/habitantStyle.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'OnlineVotation/boot/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" >
    <link href="{% static 'OnlineVotation/icons/font/css/open-iconic-bootstrap.css' %}" rel="stylesheet" type="text/css" >
</head>
<body>

    <div class="loginContainer">
        <form action="POST" class="loginForm">
            <input type="text" placeholder="DNI/NIE" title="Example: DNI - 12345678X">
            <input type="text" placeholder="Password" title="Should have at least 9 characters">
            <input type="submit" value="Login">
        </form>
    </div>

</body>
</html>

DjangoProject/mysite/OnlineVotation/templates/OnlineVotation/home/home.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    {% load static %}
    <link href="{% static 'OnlineVotation/css/homeStyle.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'OnlineVotation/boot/css/bootstrap.min.css' %}" >
</head>
<body>
<div class="container mainContainer">
    <div class="row align-items-center mainContainerRow">
            <a class="col-sm" href="{% url 'onlineVotation:habitant' %}">
                Habitant
            </a>
            <a class="col-sm" href="{% url 'onlineVotation:organizer' %}">
                Organizer
            </a>
            <a class="col-sm" href="{% url 'onlineVotation:admin' %}">
                Admin
            </a>
            <a class="col-sm" href="{% url 'onlineVotation:newUser' %}">
                New User
            </a>
    </div>
</div>


</body>
</html>

DjangoProject/mysite/OnlineVotation/templates/OnlineVotation/newUser/newUser.html
{% extends "OnlineVotation/shared/base.html" %}

{% load static %}

{% block title %}
    Habitant
{% endblock %}

{% block links %}
    <link href="{% static 'OnlineVotation/css/newUser/newUserStyle.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'OnlineVotation/js/newUserScript.js' %}" rel="script" type="text/javascript"></script>
{% endblock %}

{% block content %}
    <div>
{#        <form action="{% url 'onlineVotation:registerNewUser' %}" method="post" class="loginForm">#}
        <form action="{% url 'onlineVotation:registerNewUser' %}" method="post">
            {% csrf_token %}
{#            <div>#}
{#                <label for="your_name"></label>#}
{#                <input type="text" name="your_name" id="your_name" placeholder="Name" maxlength="100" required>#}
{#            </div>#}
            <table>
                {{ form.as_table }}
            </table>
{#            <input type="text" name="surname" placeholder="SurName">#}
{#            <input type="text" name="phoneNumber" placeholder="Phone number">#}
{#            <input type="text" name="email" placeholder="Email">#}
{#            <select name="autonomousComunity" id="autonomousComunity">#}
{#                <option value="1">Andalucia</option>#}
{#                <option value="2">Aragon</option>#}
{#                <option value="3">Galicia</option>#}
{#            </select>#}
{#            <select name="province" id="province">#}
{#                <option value="1">Malaga</option>#}
{#                <option value="2">Sevilla</option>#}
{#                <option value="3">Granada</option>#}
{#            </select>#}
{#            <input type="text" name="birthday" placeholder="Birthday" onfocus="(this.type='date')" onblur="(this.type='text')">#}
{#            <input type="password" name="pass" placeholder="Password">#}
{#            <input type="password" name="repeatPass" placeholder="Repeat password">#}
            <div class="formBtnContainer">
                <input type="submit" value="Singin">
                <input type="button" value="Reset">
            </div>
        </form>

    </div>
{% endblock %}

DjangoProject/mysite/OnlineVotation/templates/OnlineVotation/organizer/organizer.html
{% extends "OnlineVotation/shared/base.html" %}

{% load static %}

{% block title %}
    Habitant
{% endblock %}

{% block content %}
    <div>
        <p>Main Organizer page</p>
    </div>
{% endblock %}

DjangoProject/mysite/OnlineVotation/templates/OnlineVotation/shared/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    {% load static %}
    <link href="{% static 'OnlineVotation/css/baseStyle.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'OnlineVotation/boot/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" >
    <link href="{% static 'OnlineVotation/icons/font/css/open-iconic-bootstrap.css' %}" rel="stylesheet" type="text/css" >

{% block links %}

 {% endblock %}

</head>
<body>
<div class="container">
    {# Header #}
    <div class="header container">
        <div class="row">
            <div class="col-4">
                <a href="{% url 'onlineVotation:index' %}">
                    Back to main menu
                </a>
            </div>

            <div class="col-2 offset-5 align-content-end">
                <a href="{% url 'onlineVotation:index' %}">
                    Settings
                    <span class="oi oi-wrench"></span>
                </a>
            </div>
            <div class="col-1 align-content-start">
                <a href="{% url 'onlineVotation:index' %}">
                    Help
                    <span class="oi oi-question-mark"></span>
                </a>
            </div>
        </div>
    </div>

    {# Content #}
    {% block content %}

    {% endblock %}


    {# Footer #}
{#    <div class="footer">#}
{#        <div>#}
{#            <p>Footer</p>#}
{#        </div>#}
{#    </div>#}
</div>
</body>
</html>

DjangoProject/mysite/OnlineVotation/templates/OnlineVotation/shared/commonLoginPage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>OVLogin</title>
    {% load static %}
    <link href="{% static 'OnlineVotation/css/habitant/habitantStyle.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'OnlineVotation/boot/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" >
    <link href="{% static 'OnlineVotation/icons/font/css/open-iconic-bootstrap.css' %}" rel="stylesheet" type="text/css" >
</head>
<body>

<div class="loginContainer">
    <form action="POST" class="loginForm">
        <input type="text" placeholder="Reference number" title="Reference number from email">
        <input type="text" placeholder="DNI/NIE" title="Example: DNI - 12345678X">
        <input type="text" placeholder="Password" title="Should have at least 9 characters">
        <input type="submit" value="Login">
    </form>
</div>

</body>
</html>